GET http://localhost:3001/api


###
GET http://localhost:3001/api/637707c9877b77b64dc5195b
Content-Type: application/json


###
POST http://localhost:3001/api
Content-Type: application/json

{
    "nama":"jordan",
    "warna":"merah",
    "ukuran":43,
    "bahan":"kanvas",
    "jenis":"sport",
    "stock":42
}


###
GET http://localhost:3001/api/history
Content-Type: application/json


###
POST  http://localhost:3001/api/history
Content-Type: application/json

{
    "nama":"jordan",
    "sepatu_id":"merah",
    "status":"ad",
    "dari":"kanvas",
    "untuk":"sport",
    "tanggal":"sport",
    "total_Sepatu":420
}


###
DELETE   http://localhost:3001/api/history


###
GET  http://localhost:3001/api/sepatu/8bc9e8f6-5239-7523-da47-3922b0da1553
Content-Type: application/json

{
    "stock":999
}